#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT_DIR/scripts/lib/team_env.sh"

DATA_DIR="$(resolve_team_data_dir "${TEAM_PORTAL_DATA_DIR:-$(read_env_value TEAM_PORTAL_DATA_DIR)}")"
mkdir -p "$DATA_DIR/logs"

OWNER_EMAIL="${BUSINESS_INSIGHTS_GOOGLE_OWNER_EMAIL:-$(read_env_value BUSINESS_INSIGHTS_GOOGLE_OWNER_EMAIL)}"
SHEET_URL="${BUSINESS_INSIGHTS_GOOGLE_SHEET_URL:-$(read_env_value BUSINESS_INSIGHTS_GOOGLE_SHEET_URL)}"
CONFIG_ENCRYPTION_KEY="${TEAM_PORTAL_CONFIG_ENCRYPTION_KEY:-$(read_env_value TEAM_PORTAL_CONFIG_ENCRYPTION_KEY)}"
PUBLIC_GCS_BUCKET="${TEAM_PORTAL_PUBLIC_GCS_PUBLISH_BUCKET:-$(read_env_value TEAM_PORTAL_PUBLIC_GCS_PUBLISH_BUCKET)}"
CLOUD_RUN_PUBLIC_GCS_BUCKET_VALUE="${CLOUD_RUN_PUBLIC_GCS_BUCKET:-$(read_env_value CLOUD_RUN_PUBLIC_GCS_BUCKET)}"
PUBLIC_GCS_ACCOUNT="${TEAM_PORTAL_PUBLIC_GCS_PUBLISH_ACCOUNT:-$(read_env_value TEAM_PORTAL_PUBLIC_GCS_PUBLISH_ACCOUNT)}"
CLOUD_RUN_DEPLOY_ACCOUNT_VALUE="${CLOUD_RUN_DEPLOY_ACCOUNT:-$(read_env_value CLOUD_RUN_DEPLOY_ACCOUNT)}"
export TEAM_PORTAL_DATA_DIR="$DATA_DIR"
export BUSINESS_INSIGHTS_GOOGLE_OWNER_EMAIL="$OWNER_EMAIL"
export TEAM_PORTAL_CONFIG_ENCRYPTION_KEY="$CONFIG_ENCRYPTION_KEY"
if [[ -n "$SHEET_URL" ]]; then
  export BUSINESS_INSIGHTS_GOOGLE_SHEET_URL="$SHEET_URL"
fi
if [[ -n "$PUBLIC_GCS_BUCKET" ]]; then
  export TEAM_PORTAL_PUBLIC_GCS_PUBLISH_BUCKET="$PUBLIC_GCS_BUCKET"
fi
if [[ -n "$CLOUD_RUN_PUBLIC_GCS_BUCKET_VALUE" ]]; then
  export CLOUD_RUN_PUBLIC_GCS_BUCKET="$CLOUD_RUN_PUBLIC_GCS_BUCKET_VALUE"
fi
if [[ -n "$PUBLIC_GCS_ACCOUNT" ]]; then
  export TEAM_PORTAL_PUBLIC_GCS_PUBLISH_ACCOUNT="$PUBLIC_GCS_ACCOUNT"
fi
if [[ -n "$CLOUD_RUN_DEPLOY_ACCOUNT_VALUE" ]]; then
  export CLOUD_RUN_DEPLOY_ACCOUNT="$CLOUD_RUN_DEPLOY_ACCOUNT_VALUE"
fi

cd "$ROOT_DIR"
exec "$PYTHON_BIN" "$ROOT_DIR/scripts/refresh_business_insights_from_google_sheet.py"
